### ISSUE TITLE
🐛 Error gets displayed, when initially overriding a deployed Diagram

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1262] opened 2019-01-10 14:16 UTC
#### Describe your issue

When trying to override an already deployed Diagram, an error message is displayed. 

```
SomethingSomething ManagementApi - Not Found
```

![screenshot 2019-01-10 at 15 16 17](https://user-images.githubusercontent.com/38498731/50974090-b7333500-14ea-11e9-8981-f90992702e47.png)

#### How can others reproduce the issue?

* Deploy a Diagram (Make sure its not already deployed)
* Switch to the FileSystem View of this Diagram
* Make some changes
* Try to deploy it again

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment] 2019-01-10 14:56
I can not reproduce this Issue.
I already had this error when my backend was broken or out of date, could you check if this also happens with a clean backend? (But please make a backup of your old backend)

**Comment by Vyperus** [comment] 2019-01-21 14:21
I can't reproduce this on develop either. Closing this for now. Feel free to reopen it if the error reoccurs @robpal94

**Closed by Vyperus** 2019-01-21 14:21 UTC
