### ISSUE TITLE
🚸 Only an empty Window is shown, when the Identity Server is not Reachable

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1308] opened 2019-01-24 13:48 UTC
#### Describe your issue

When the Identity Server is not reachable, only a white / empty window opens. There is not error message displayed which informs the user, that the Identity Server could not be reached.

#### How can others reproduce the issue?

* Try to login at an Authority, which is not reachable
* See, that only a white with no associated error message opens

#### Possible solution

Display an error message to let the User know, that the Authority on which he wants to log in could not be reached. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment] 2019-02-19 10:46
I tested this with the latest version of BPMN-Studio (4.21.0) and couldn't reproduce this issue.

Closing this for now.

**Closed by Vyperus** 2019-02-19 10:46 UTC
Labels: Bad User Experience, Bug
