### ISSUE TITLE
Resize Function Breaks

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/bpmn-studio#204] opened 2018-03-15 08:04 UTC
#### Describe your issue

The resize function breaks in some cases.
One way to break it is resizing the Property-Panel and clicking out of the browser.
Another way to break it is clicking the resize button several times. 
Pressing the Hide and the Show button again fixes the resize function temporarily.

![resize_bug](https://user-images.githubusercontent.com/20394992/37511855-99c5cbc6-2900-11e8-9876-af01f1e3f470.gif)

#### How can others reproduce the issue?

- Open up Detail-View of a ProcessDefiniton
- Resize Property-Panel
- While Resizing click out of the Browser
- Try to resize Property-Panel again

or

- Open up Detail-View of a ProcessDefiniton
- Click the Resize Button numerous times
- Try to resize Property-Panel

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by alexanderkasten** [comment] 2018-03-16 08:36
I can't reproduce this issue

**Comment by MiguelACarballo** [comment] 2018-03-16 08:43
@alexanderkasten I can reproduce it

**Comment by SteffenKn** [comment] 2018-03-16 09:01
@alexanderkasten @MiguelACarballo I updated the Issue. Now everyone should be able to reproduce this issue.

**Comment by LeoTT** [comment] 2018-04-24 14:38
fixed in #262

**Closed by LeoTT** 2018-04-24 14:38 UTC
Labels: bug
