### ISSUE TITLE
About window missing

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#660] opened 2018-07-27 09:02 UTC
#### Describe your issue
When you click _bpmn-studio -> About bpmn-studio_ nothing happens.
We should implement just a basic _about_ dialog which contains some basic informations.

#### How can others reproduce the issue?
* Click at _bpmn-studio_ in the menu bar
* Click at _About bpmn-studio_

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment] 2018-07-27 09:04
Duplicate of https://github.com/process-engine/bpmn-studio/issues/384

**Closed by Paulomart** 2018-07-27 09:04 UTC
Labels: enhancement, windows
