### ISSUE TITLE
edit layout of 'Form' ui

### ISSUE THREAD

**Issue by SORC3r3r** [process-engine/bpmn-studio#33] opened 2017-10-24 07:07 UTC
#### Describe your issue

In my model I'd like to use the decision I make in a 'Form' UI to follow different paths in my flow.
If I use a 'Confirm' UI, I am able to use the keys which I set in the 'uiConfig' layout to follow different paths in my flow. For the 'Form' UI that seems to be not possible.

So it would be nice to use 
`${ "message": "My message", "layout": [ { "key": "confirm", "label": "OK"}, { "key": "decline", "label": "Cancel"}] };`
in the 'Form' UI as well.

#### How can others reproduce the issue?

1. Create a user task 'uiName-Form' with the above 'uiConfig'
2. connect the user task to an ExclusiveGateway
3. connect the ExclusiveGateway to two new tasks
4. in the two SequenceFlow's add the condition type 'expression'
5. add the following Expressions
`this.history.userspace_approve.key === 'confirm' `
`this.history.userspace_approve.key === 'decline' `
6. start the process

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by alexanderkasten** [comment] 2017-11-07 15:19
@SORC3r3r I can't reproduce the issue, can you export your diagram and upload it ?

**Comment by SORC3r3r** [comment] 2017-11-07 15:42
[test.zip](https://github.com/process-engine/charon/files/1450601/test.zip)

@alexanderkasten I attached a sample.
It won't work because you can not configure the keys of the Form UI as you can in Confirm UI.

**Comment by SORC3r3r** [comment] 2017-11-09 09:42
@alexanderkasten The default labels for the uiName-Form Buttons is 'Abbrechen' and 'Weiter'.
Is there any way to change that with a uiConfig property or something else right now?

**Comment by heikomat** [comment] 2017-12-11 10:10
@SORC3r3r commit cfa43fa says it closes this issue. Can you confirm, that the original issue is solved?

**Comment by Paulomart** [comment] 2017-12-11 10:45
The commit seems to mention the wrong issue..

**Comment by SteffenKn** [comment] 2018-10-12 13:42
Do we want to support this?

**Comment by cmg-dev** [comment] 2018-10-15 14:08
This referee to an old mechanism regarding the UserTasks, the Layout Parameter is not supported anymore in this.

Please stay tuned, until the Dynamic UI part of the Consumer API is in place.

It will include this capability and many more.

It will be in the Roadmap in Q1 2019.

**Closed by cmg-dev** 2018-10-15 14:08 UTC
Labels: Needs Review, feature
