### ISSUE TITLE
:bug: Process Without Lane Broken

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/bpmn-studio#792] opened 2018-08-14 09:00 UTC
## Describe your issue

If a process has no lane, the studio is unable to save changes, but reports "Successfully saved!". 

## How can others reproduce the issue?

Use this file in BPMN-Studio 4.0.1.:

[MyActorSystem.DemoProcess.broken.bpmn.zip](https://github.com/process-engine/bpmn-studio/files/2286203/MyActorSystem.DemoProcess.broken.bpmn.zip)

You will be unable to save any changes to it!

This file is a correct working example, but it has a lane:

[MyActorSystem.DemoProcess.bpmn.zip](https://github.com/process-engine/bpmn-studio/files/2286193/MyActorSystem.DemoProcess.bpmn.zip)

#### Possible solution

Correct it.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment] 2018-08-16 15:50
With my simple [sample process](https://gist.github.com/robpal94/0748c36cabb6f172af1cfbb707083290) it works without a problem. However, the Sample Process still contains a 
```
<bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_0hc6ufy">
```
definition.

**Comment by Vyperus** [comment] 2018-08-28 08:29
I can't reproduce this Issue on version 4.2.0 of BPMN-Studio. However after the update of diagram-js it will now throw this error which i think is totally fine:

<img width="762" alt="bildschirmfoto 2018-08-28 um 10 27 08" src="https://user-images.githubusercontent.com/17248802/44710720-11d47300-aaad-11e8-8749-08e5403a0b7a.png">

The error message explains what the user is doing wrong and basically how he could fix this. It also explains why it wasn't saved in the first place. With this Information I'm closing this Issue for now.

**Closed by Vyperus** 2018-08-28 08:29 UTC
Labels: bug
