### ISSUE TITLE
BPMN Diff layout not working properly

### ISSUE THREAD

**Issue by 5ebastianMeier** [process-engine/bpmn-studio#754] opened 2018-08-03 18:55 UTC
#### Describe your issue

I noticed that the layout seems a bit strange on the BPMN Diff.

![drag_error_1](https://user-images.githubusercontent.com/16539774/43659628-dd76fd34-975c-11e8-95bb-e5edb3493a94.PNG)

##### Problem 1
It doesn't use the whole horizontal space.

##### Problem 2
The diff log doesn't support scrolling.
Also the control feels a bit poor, because there is no frame for it and most importantly, there are no controls or handles to customize the size.

##### Problem 3
The diff log on the bottom right breaks the layout concept.

Any area a component wants to use in the main area should either be
* a floating popup (not docked to the sides)
* a docked area stretched vertically or horizontally

Otherwise we have tools that overlap with other areas of the mainarea and might
* hide content or other controls
* brake our layout because other tools might behave the same way and try to take up the same place

##### Problem 4
This is closely attached to Problem 3.

The diff log seems to overlap the bottom third that display the diff result.
This results in a faulty dragging experience, because you can suddenly drag the content in the bottom third outside of the viewing field. At the same time the other two panels still show the content in their boundaries.

![drag_error_2](https://user-images.githubusercontent.com/16539774/43659629-dd92de0a-975c-11e8-9d8a-bfadc4fa2878.PNG)

##### Solution 1

The right side remains unused where it would be easy to stretch the diff areas to 100% width like this:

![drag_error_soll](https://user-images.githubusercontent.com/16539774/43659627-dd5b7e4c-975c-11e8-933f-939b15436949.PNG)

##### Solution 2
* Support scrolling
* Add toggle filters for categories (Change, Added, Layout Changed)

##### Solution 3
Since the log messages are not very long we should display it:
* on the right side
* stretched to 100% height

The control buttons should be placed on the bottom, because the other menu items related to this are also placed there and the travel distance between them shouldn't be from top to bottom.

There should also be a button to switch to a horizontally stretched version if someone prefers that layout. But that's rather optional, because it will likely waste a lot of space (short log messages).

##### Solution 4
Should be solved when the height is strechted to 100% and it doesn't overlap with differ component anymore.

#### What's your setup

- Windows 10

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment] 2018-08-03 19:43
This is certainly a windows issue, the macOS-version looks much nicer.

It should definetly look like the macOS-version.

Can you please share some graphic settings? Resolution and such.

**Comment by 5ebastianMeier** [comment] 2018-08-03 19:51
My resolution is 2560x1440, but I only used it in window mode and made it wider to fit the dev tools next to them - the dev tools showed a window size of about 1280x740.

Otherwise I got nothing special, just Windows 10 with latest updates.

**Comment by cmg-dev** [comment] 2018-08-03 19:54
@Vyperus we should split this issue into several smaller ones.

**Comment by SteffenKn** [comment] 2018-08-06 07:53
1. The issue here is simply that the "Before"- and the "After"-BPMN-Viewer does not get placed next to each other.

2. The Change List should be scrollable as soon as there are enough changes. In your case it looks like there are not enough changes to make it scrollable.

3. Resizing is planned as you can see in issue #541.

4. One could think about different views to make it look like in this screenshot:
> ![image](https://user-images.githubusercontent.com/20394992/43703846-54accd4a-995e-11e8-81a8-8e7a277ab9f7.png)
I am going to add this to #541 as well.

**Comment by 5ebastianMeier** [comment] 2018-08-07 07:04
I remember that during my test, there were 5 items in the list and only 4 of them were displayed without showing a scrollbar.

I'll try to reproduce this again.

**Comment by SteffenKn** [comment] 2018-08-07 07:15
Maybe it was just not displayed because of your broken layout? If you can reproduce this with a working layout this is definitely a bug.

**Comment by Vyperus** [comment] 2018-09-11 12:59
I tested this with version 4.3.0 of BPMN-Studio and wasn't able to reproduce this again. 

<img width="1680" alt="bildschirmfoto 2018-09-11 um 14 58 23" src="https://user-images.githubusercontent.com/17248802/45361730-3ebb7680-b5d3-11e8-8bf3-9a2a78cee990.png">

Closing this for now.

**Closed by Vyperus** 2018-09-11 12:59 UTC
Labels: bug, windows
