### ISSUE TITLE
✨ Allow Resizing of the SolutionExplorer

### ISSUE THREAD

**Issue by Paulomart** [process-engine/bpmn-studio#576] opened 2018-07-18 08:16 UTC
#### Describe your issue

Cannot resize the solution explorer

#### How can others reproduce the issue?

Try to resize

#### Possible solution

Allow resizing the solution explorer

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by SteffenKn** [comment] 2018-10-12 14:21
Duplicate of #344

**Closed by SteffenKn** 2018-10-12 14:21 UTC
Labels: enhancement, feature
