### ISSUE TITLE
🚸 Can't copy/move Process to another ProcessEngine

### ISSUE THREAD

**Issue by robpal94** [process-engine/bpmn-studio#1338] opened 2019-02-08 08:31 UTC
#### Describe your issue

Its not possible to move a ProcessModel, which is stored on one ProcessEngine to another one. When trying to export the ProcessModel and redeploy it, the _Select Target Destination_ Modal is not shown. Instead, the ProcessModel is always redeployed to the source ProcessEngine. 

Btw: If the ProcessModel is stored on both connected ProcessEngines, the Modal with the Destination Selection is displayed as it should. 

#### How can others reproduce the issue?

* Deploy a Diagram to one ProcessEngine
* Connect to another ProcessEngine
* Try to deploy the ProcessModel to the connected ProcessEngine
* See, that no _Select Destination_ modal is shown and the ProcessModel is always redeployed to the ProcessEngine, which already has this ProcessModel stored.

#### Possible solution

Always display the _Select Destination_ Modal (even if a ProcessModel with the same name exists on a connected ProcessEngine). 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment] 2019-02-19 13:07
Following the instructions given in this issue i was not able to reproduce this behavior.

It wouldn't make much sense anyway since the there is only one check that determines if the modal is shown or not.
And that check only checks of there is more than one remote solution connected to the studio.

Correct me if I am wrong.
Closing this for now.

**Closed by Vyperus** 2019-02-19 13:07 UTC
Labels: Bad User Experience
