### ISSUE TITLE
🐛Fix Autoupdate Mechanism for Windows

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/bpmn-studio#739] opened 2018-08-03 13:09 UTC
## Describe your issue

For since the release of BPMN-Studio 4.0, we have turned off the autoupdate mechanism on windows.
It always runs in an electron specific error.

## Possible solution

Update to electron 2.0; fix the updater.

## What's your setup

- OS: Windows, All Versions:

## Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

Related:

#705 
#715

**Comment by SteffenKn** [comment] 2018-10-10 10:02
Duplicate of #715

**Closed** 2018-10-15 08:00 UTC
Labels: bug, duplicate, windows
