### ISSUE TITLE
Delete process breaks other processes feasibility

### ISSUE THREAD

**Issue by SORC3r3r** [process-engine/bpmn-studio#52] opened 2017-11-03 10:27 UTC
#### Describe your issue

Deleting a process causes all other processes to be not executable.
Restarting the server or Charon does not help.
Only thing that helped was dropping the database and start from scratch.

#### How can others reproduce the issue?

If you do not have any processes, create a new process with simple UserTask.
Execute the process and verify that the task is listed in the task list.
Create another process with a simple UserTask.
Execute the new process to confirm its feasibility.
Delete one of the processes.
Start the other process and see no task in the task list.

#### What's your setup

- OS (`Windows/OS X/Linux` + `version`): Ubuntu 17.0.4
- Node (`node --version`): 7.10.1
- NPM (`npm --version`): 4.2.0
- Docker (`docker version --format '{{.Server.Version}}'`):
- Chrome

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment] 2017-11-16 14:26
I cannot reproduce your issue using these processes: [processes.zip](https://github.com/process-engine/charon/files/1478845/test.zip).

I did the following steps:

- Created test1 using `Prozess erstellen`-Process
- Created test2 using `Prozess erstellen`-Process
- Edited test1 to render some simple ui
- Edited test2 to render some simple ui (did not import/export from test1)
- Started test1 -> Listed under tasks -> Finished
- Started test2 -> Listed under tasks -> Finished
- Started test1 && test2 -> Both listed under tasks -> Finished both -> No longer listed
- Started test1, then deleted test2 -> Listed under tasks -> Finished

@SORC3r3r could you please test your setup again and see if it works now? This issue may not be caused directly by Charon.

**Comment by SORC3r3r** [comment] 2017-11-16 15:01
After you deleted the test2 process, could you still start the test1 process?

**Comment by Paulomart** [comment] 2017-11-16 18:57
Yes

**Comment by SORC3r3r** [comment] 2017-11-17 07:47
Ok, I will check again

**Comment by alexanderkasten** [comment] 2017-11-20 14:23
@Paulomart  @SORC3r3r  I can reproduce the issue.
You must start both processes and delete one of them, before the task finished.
After that, the task list shows `No tasks found`. Now you have just the possibility to see the tasks through the `Tasks` button on the detail view.

**Comment by heikomat** [comment] 2017-11-29 14:17
This is because the userTask references a process-definition that no longer exists, thus querying it fails.

A fix would be to have the necessary process-definition information in every process-instance, so that a process-instance doesn't rely on the original process-definition.

This would also mean that we have to query the process-definition of the porcess-instance of a node, instead of querying the process-definition of a node.

We'd need to identify all places where process-definitions are referenced, then check if the place needs to be updated to reference the process-definition info via the process-definition, update the places and test if everything still words.

Depending on the number of places that need to be changed, this is most likely less then a PT of pure implementation, i'd say 1 to 1.5 PT for implementation + test + PR etc. @cmg-dev

**Comment by ppoetschke** [comment] 2017-11-29 14:39
@heikomat @cmg-dev I don't see it as a useful solution to copy the whole definition with each start of a process mainly for performance reasons.

I would solve it as a constraint to either not allow deleting process definitions, if there are running processes or to abort running processes and delete linked instances of processes and nodes together with related the definition. Anyway, deleting process definitions should only be possible over the management api.

As long as the management api is not specified I would postpone this issue as it's not really a blocker.

**Comment by heikomat** [comment] 2017-11-29 15:33
@ppoetschke most of the fix would not be part of the management-api. It is correct, that deleting should happen through the management-client as soon as we have it, but the fix is mostly adding information about the process-definition to the process-instance and that accessing that instead wherever applicable.

This is mostly a fix on the processEntity. I would suggest cloning all values of the definition over to the instance on creation, to fields that are prefixed with `process_model_` @cmg-dev

**Comment by heikomat** [comment] 2017-11-29 15:35
I would also suggest to remove the `processDef` field from the process-instance. The process-instance should ideally have all information, and not rely at all on the definition it was originale spawned from

**Comment by ppoetschke** [comment] 2017-11-29 16:34
I suggest to move this discussion in the concept area. This is too far away from the original problem and your proposals would have deeper architectural side effects imho.

**Comment by heikomat** [comment] 2017-12-04 08:29
i thought about another solution, which encompasses saving a new version of a model, every time something in the model changed. This would result in no instance ever referencing a non-existing model.

With this we'd never be able to delete any version of a model, that was ever referenced by a process-instance. This is however not a problem if we just introduce a deleted-timestamp for the models.

Another thing to consider with this: the draft-flag/draft-process. who has what exact requirements regarding the draft-process? Maybe using this idea could make the draft-flag obsolete. If not: why not? What are the requirements?

\cc: @5ebastianMeier @cmg-dev @ppoetschke

**Comment by Paulomart** [comment] 2018-09-13 08:44
This issue outdated and likely fixed in the latest version. Its also no longer possible to delete processes within BPMN Studio.

**Closed by Paulomart** 2018-09-13 08:44 UTC
Labels: Not a BPMN-Studio bug, bug
